spring:
  application:
    name: mod2-spring-core-task
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:h2:~/test
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2.console.enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd'T'HH:mm}){yellow} %clr(%marker){blue} %clr([${LOG_LEVEL_PATTERN:%5p}]) [%X{txID}] %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
  level:
    ROOT: INFO
    org:
      springframework:
        transaction: DEBUG
        orm:
          jpa: DEBUG
# my.properties.trainees-data-file=src/main/resources/mock-data/trainees-data.json
# my.properties.trainers-data-file=src/main/resources/mock-data/trainers-data.json
# my.properties.training-data-file=src/main/resources/mock-data/training-data.json
# logging.structured.format.console=com.epam.dalvaradoc.mod2_spring_core_task.configs.CustomLoggerFormatting
